### PR TITLE
Async requests using aiohttp

### PR DESCRIPTION
**Pull request by sbscully**

### CODE REVIEW

**Comment by sbscully** [comment]
@mtmail I've got async requests working, the following works in the console:

```python
import asyncio
from opencage.geocoder import OpenCageGeocode

def run():
    async with OpenCageGeocode('<API-KEY>') as geocoder:
        results = await geocoder.geocode_async('EC1M 5RF')
        print(results)

loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

I'm still figuring out how to run async tests.

**Comment by sbscully** [comment]
@mtmail I'm having trouble with mocking out HTTP calls in async tests. I can run the async test without mocking just fine, but couldn't get `aiohttpretty` or `aioresponses` libraries to work for mocking. Do you have any ideas about what to use?

Also, I accidentally checked in my API key, but I've disabled it so it shouldn't matter.

**Comment by mtmail** [comment]
I had a look last Friday, then got distracted again. geopy seems to solve it by adding a wrapper. We can also use our new test API keys https://opencagedata.com/api#testingkeys Those are safe to use in test suites.

**Comment by sbscully** [comment]
@mtmail I've got the tests working. Having a look at the example script.

**Comment by sbscully** [comment]
I've included the batch script in `examples/batch.py`. I got it to run using the test API key, swapped in my own API key and it was hanging, not sure why. I think that's everything done now though.

**Pull request merged**
